### ISSUE TITLE
Unable to load DLL 'oci': Não foi possível encontrar o módulo especificado. (Exception from HRESULT: 0x8007007E)

### ISSUE THREAD

**Issue by alissonsolitto** [ericmend/oracleClientCore-2.0#10]
Estou com esse erro e ainda não consegui resolver, efetuei o download do client Oracle (instantclient_12_2) e descompactei no "C:\", inclui as variáveis de sistema, mas mesmo assim no momento de abrir a conexão recebo este erro.

Estou utilizando o .NET CORE 2 + DAPPER.

**ERRO = Unable to load DLL 'oci': Não foi possível encontrar o módulo especificado. (Exception from HRESULT: 0x8007007E)**

**Comment by dubo** [comment]
Can you write :
OS  version  ( 32/64 bit) ?
Oracle client software version (32/64 bit) ?
Eric has bug in readme: In Windows path must be set as:   PATH=%PATH%;"C:\instantclient_12_2" not PATH=$PATH:"C:\instantclient_12_2"

**Comment by alissonsolitto** [comment]
Consegui resolver o problema incluindo não somente as variáveis de sistema, mas também as variáveis no ambiente de usuário.

SO = Windows 10 (x64)
Client Oracle = 12.2 (x64)

**Comment by dubo** [comment]
this works for me:

- download

  http://download.oracle.com/otn/nt/instantclient/122010/instantclient-basic-windows.x64-12.2.0.1.0.zip

- unzip to c:\instantclient_12_2

- create file tnsnames.ora in c:\instantclient_12_2\network\admin  e.g. c:\instantclient_12_2\network\admin\tnsnames.ora with your settins

- in System/Advanced system settings/Enviroment variables add System or User variable 
OCI_HOME  =  c:\instantclient_12_2
- in System/Advanced system settings/Enviroment variables add  to System or User Path variable
value c:\instantclient_12_2

- you can set  NLS_LANG too,    SLOVAK_SLOVAKIA.UTF8 for me , 
BRAZILIAN PORTUGUESE_BRAZIL.WE8ISO8859P1  or PORTUGUESE_PORTUGAL.WE8MSWIN1252  for you

This settings you can set too in terminal , or in  your debug options - enviroment variables in Visual studio

You can try my sample  https://github.com/dubo/oracleClientCore-Sample

**Comment by alissonsolitto** [comment]
Thank you! Thank you!
It was the perfect solution to the problem, including the **NLS_LANG** configuration.
