### ISSUE TITLE
Timeout doesn't work

### ISSUE THREAD

**Issue by Pradhyo** [ericmend/oracleClientCore-2.0#12]
I tried what's [here](https://msdn.microsoft.com/en-us/library/system.data.oracleclient.oraclecommand.commandtimeout(v=vs.110).aspx) but it fetched data beyond the timeout I set in seconds.

```c#
      using (OracleConnection connection = new OracleConnection(connectionString))
      {
        OracleCommand command = new OracleCommand(selectStatement, connection);
        command.Connection.Open();

        using (OracleDataAdapter da = new OracleDataAdapter(command))
        {
          da.SelectCommand.CommandTimeout = 30;
          da.Fill(dataTable);
          command.Connection.Close();
          da.Dispose();
        }
      }
```

**Comment by ericmend** [comment]
Olá @Pradhyo . Recomendo a você, usar o nuget, ainda beta, da Oracle:
https://www.nuget.org/packages/Oracle.ManagedDataAccess.Core

**Comment by Pradhyo** [comment]
Thanks for getting back.
