### ISSUE TITLE
No license of OracleClientCore-2.0

### ISSUE THREAD

**Issue by CoderGeoff** [ericmend/oracleClientCore-2.0#3]
Hi there, 
This package looks like the perfect answer to our issues connecting to an Oracle database from .NET Core. Except that I can't find any license information, and we can't use it unless we can show that we are legally entitled to! Would you be willing to add a license? Something like an MIT licence (see [here](https://choosealicense.com/) for a discussion of open source licenses) would work fine for us. 
Cheers,
Geoff

**Comment by ericmend** [comment]
Olá Geoff,

Licença criada com sucesso!!

Eu também estou tentando quebrar essas barreiras dentro da empresa onde trabalho :D

Obrigado por contribuir para a comunidade ;-)
*Desculpe pelo português. Mas o meu inglês é ainda pior :D

**Comment by CoderGeoff** [comment]
Hola Eric.
Muchas gracias por eso y por la repuesta tan rápido. Y discuplarme por escribir in espanol - no es difícil entender portugués escrito, pero no puedo escribirlo mi mismo ;-)

**Comment by ericmend** [comment]
;-)
